/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarCalendarIdRouteImport } from './routes/calendar.$calendarId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarCalendarIdRoute = CalendarCalendarIdRouteImport.update({
  id: '/calendar/$calendarId',
  path: '/calendar/$calendarId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar/$calendarId': typeof CalendarCalendarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar/$calendarId': typeof CalendarCalendarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar/$calendarId': typeof CalendarCalendarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar/$calendarId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar/$calendarId'
  id: '__root__' | '/' | '/calendar/$calendarId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarCalendarIdRoute: typeof CalendarCalendarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$calendarId': {
      id: '/calendar/$calendarId'
      path: '/calendar/$calendarId'
      fullPath: '/calendar/$calendarId'
      preLoaderRoute: typeof CalendarCalendarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarCalendarIdRoute: CalendarCalendarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
